### ISSUE TITLE
Feature request: show jurisdiction

### ISSUE THREAD

**Issue by tomlurge** [vtduncan/asn-geo#1]
Would it be possible to show the country in which an AS is legally based in addition to its geo location? That would show the "juristical" location of an AS. Might be useful to spot easily if e.g. an AS is located in a Five Eyes country, if it is under the control of a specific government etc.

**Comment by vtduncan** [comment]
Yep, the country code is listed in `GeoLiteCity-Location` right alongside lat/lon. I'll add it when I get a chance.

**Comment by vtduncan** [comment]
Done! Added in 23ee16f3.

**Comment by tomlurge** [comment]
Hey, very cool! Say I want to use that in my tool, visionion. Do you provide a public API, a webservice? Probably not. If I install as-geo on my server, alongside visionion, how often would I have to update the Geo-files to stay current? Is that feasable (from your experience)?

Thanks!
Thomas


On 08 Oct 2015, at 17:14, Duncan <notifications@github.com> wrote:

> Done! Added in 23ee16f.
> 
> �
> Reply to this email directly or view it on GitHub.
> 



+
thomas l�rtsch + hospitalstr. 95 + d 22767 hamburg      
+49 173 202 71 99 + tl@rat.io + tomlurge@someOtherServices

++
http://manyfacesofnadiya.tumblr.com/

**Comment by vtduncan** [comment]
Correct, there is no web service. Just copy the SQLite database to your own application. I don't have much experience with the GeoIP dataset but I think they update it weekly.

**Comment by tomlurge** [comment]
ok, thanks again!
t.


On 08 Oct 2015, at 18:00, Duncan <notifications@github.com> wrote:

> Correct, there is no web service. Just copy the SQLite database to your own application. I don't have much experience with the GeoIP dataset but I think they update it weekly.
> 
> �
> Reply to this email directly or view it on GitHub.
> 



+
thomas l�rtsch + hospitalstr. 95 + d 22767 hamburg      
+49 173 202 71 99 + tl@rat.io + tomlurge@someOtherServices

++
http://manyfacesofnadiya.tumblr.com/
